name: Monopoly
version: ${project.version}
main: io.guthub.kbatesCS.monopoly.Main
api-version: 1.15
authors: [MasterBea]
description: monopoly plugin
commands:
  createGame:
    description: starts the monopoly game, creates a board with it
    usage: /createGame [player] [player]....
  join:
    description: joins a monopoly name
    usage: /join <game number> <Block>
  startGame:
    description: starts a game
    usage: /startGame <gamenum>
  endGame:
    description: end a game
    usage: /endGame <gamenum>
  trade:
    description: trade with a player
    usage : /trade <player name>